#!/bin/bash

set -eu

install-packages git-core wget make gcc python-pip python-dev python-setuptools python-virtualenv chef puppet

name=oasis-agent
svc_root=${DIB_OASIS_AGENT_SVC_ROOT:-/opt/stack/$name}
install_dir=${DIB_OASIS_AGENT_INSTALL_DIR:-/opt/stack/$name}
repo=${DIB_OASIS_AGENT_REPO:-git://git.openstack.org/openstack/murano-agent.git}
branch=${DIB_OASIS_AGENT_BRANCH:-master}
ref=${DIB_OASIS_AGENT_REF:-''}

# clone oasis-agent source code into /opt/stack/oasis-agent
mkdir -p $svc_root
git clone --depth=1 -b $branch $repo $svc_root
if [ -n "$ref" ]; then
    pushd $svc_root
    git fetch $repo $ref && git checkout FETCH_HEAD
    popd
fi

# install oasis-agent into virtualenv at /ops/stack/venvs/oasis-agent
virtualenv $install_dir
$install_dir/bin/pip install $svc_root

# setup config file at /etc/oasis/agent.conf
mkdir -p /etc/oasis

pushd ${svc_root}
${install_dir}/bin/oslo-config-generator --config-file ${svc_root}/etc/oslo-config-generator/oasisagent.conf
popd

cp ${svc_root}/etc/oasisagent/oasisagent.conf.sample /etc/oasis/agent.conf.sample

# mkdir function directory
mkdir -p /etc/oasis/functions

# install upstart script for oasis-agent
if [ -d "/etc/init/" ]; then
    install -D -g root -o root -m 0755 $(dirname $0)/oasis-agent.conf /etc/init/
fi
if [ -d "/etc/systemd/system/" ]; then
    install -D -g root -o root -m 0755 $(dirname $0)/oasis-agent.service /etc/systemd/system/
fi

